### PR TITLE
implement unit testing and allow pygithub.py to sync fork branch that already exists

### PR DESCRIPTION
**Pull request by eveliososa**
The previous functionality was not able to sync the fork branch from the upstream branch. It is now able to do so, and allows us to remove the function create_branch_from_upstream.

Implementations:
*Unit testing for githubfork.py
*Fixes linting errors for githubfork.py
*Creates GitHub Action to run pytest on future pull request.

The latest github action run can be found here: https://github.com/eveliososa/PyGithubFork/runs/2081235725?check_suite_focus=true

### CODE REVIEW

**Comment by hassenius** [comment]
Thanks @eveliososa .
I wonder, for the unit testing, did you have a chance to look at leveraging the mockups that the upstream pygithub project has: https://github.com/PyGithub/PyGithub/blob/master/tests/Framework.py ?

**Comment by eveliososa** [comment]
@hassenius 
I looked into the mock-ups but there was not any clear documentation on how to implement them. I'm wondering if for our classes, would it necessary to mock the GitHub objects or would having a repository to call the GitHub API be sufficient?

**Comment by hassenius** [comment]
There are a couple reasons it would be beneficial with mocks
1. Unit tests should limit the scope of what they test (i.e. they should only test the unit of work within the method that they are testing, not everything around it like the Github API, network, etc -- everything that is actually involved in making a real API call).
2. Working with a real system can cause issues for unit tests, as commonly it's desirable to test failure scenarios as well as happy path. This can be tricky when it comes to the things this repo is dealing with (i.e. forking, syncing, etc), and external factors can relatively break the unit tests without that making any reflection on the validity of the code.
3. Secrets generally aren't available for forked PR jobs (turns out that the GITHUB_TOKEN is an exception: https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow so don't necessarily apply with this exact setup).

While the pygithub framework is not well documented, apart from what's here: https://github.com/PyGithub/PyGithub/blob/master/CONTRIBUTING.md#automated-tests

you might find that using httpretty directly would probably be quicker and easier. You can see an example here: https://gist.github.com/edthrn/ce28cb1a8a86caab0129a302d8c2bc33

**Comment by eveliososa** [comment]
Made the changes to mock all GitHub API calls so that only the functionality of the code is tested and not external sources. The unit tests were ran locally and passed all scenarios as shown below:
Screen Shot 2021-03-12 at 9 46 35 AM

**Review by greenegeek — APPROVED** [review]

**Pull request merged**
